<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ResourceFlow.Application\ResourceFlow.Application.csproj" />
    <ProjectReference Include="..\ResourceFlow.Domain\ResourceFlow.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
    <Folder Include="Persistence\EF\Context\" />
    <Folder Include="Persistence\EF\Configurations\" />
    <Folder Include="Persistence\EF\Migrations\" />
    <Folder Include="Persistence\EF\Repositories\" />
    <Folder Include="Persistence\Dapper\" />
  </ItemGroup>

</Project>
