// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceFlow.Infrastructure.Persistence.EF.Context;

#nullable disable

namespace ResourceFlow.Infrastructure.Persistence.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119060856_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Billing", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillingId"));

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanySubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InvoicePdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("SubscriptionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BillingId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Billing", (string)null);
                });

            modelBuilder.Entity("CompanyDetails", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanySubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyDetails", (string)null);
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authentication.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(2168),
                            IsDeleted = false,
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(2169),
                            IsDeleted = false,
                            RoleName = "CompanyAdmin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(2170),
                            IsDeleted = false,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authentication.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastFailedLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 985, DateTimeKind.Utc).AddTicks(9282),
                            Email = "suhailpalakkal1@gmail.com",
                            FailedLoginAttempts = 0,
                            IsActive = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            PassWord = "$2a$11$0U.y8.1SpHygeDux.ZT7iucUpu8sPoUgThcbZrXggS.ri.uMIgXa.",
                            RefreshToken = "",
                            RoleId = 1,
                            UserName = "Suhail"
                        });
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authorization.AppModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AppModules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8375),
                            IsDeleted = false,
                            Name = "User Management"
                        },
                        new
                        {
                            Id = 2,
                            Code = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8377),
                            IsDeleted = false,
                            Name = "Company Details"
                        },
                        new
                        {
                            Id = 3,
                            Code = 4,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8378),
                            IsDeleted = false,
                            Name = "Company Floor",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = 5,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8380),
                            IsDeleted = false,
                            Name = "Resource Type"
                        },
                        new
                        {
                            Id = 5,
                            Code = 6,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8381),
                            IsDeleted = false,
                            Name = "FeedBack"
                        },
                        new
                        {
                            Id = 6,
                            Code = 7,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8382),
                            IsDeleted = false,
                            Name = "Employee Management"
                        },
                        new
                        {
                            Id = 7,
                            Code = 8,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8383),
                            IsDeleted = false,
                            Name = "Subscription Plans"
                        },
                        new
                        {
                            Id = 8,
                            Code = 9,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8384),
                            IsDeleted = false,
                            Name = "Resource Management",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            Code = 10,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8386),
                            IsDeleted = false,
                            Name = "Subscription Types",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 10,
                            Code = 11,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8387),
                            IsDeleted = false,
                            Name = "Company Subscriptions",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 11,
                            Code = 12,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8388),
                            IsDeleted = false,
                            Name = "Payment",
                            ParentId = 10
                        },
                        new
                        {
                            Id = 12,
                            Code = 13,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8389),
                            IsDeleted = false,
                            Name = "Billing",
                            ParentId = 10
                        },
                        new
                        {
                            Id = 13,
                            Code = 14,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8391),
                            IsDeleted = false,
                            Name = "Subscription History",
                            ParentId = 10
                        },
                        new
                        {
                            Id = 14,
                            Code = 15,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8392),
                            IsDeleted = false,
                            Name = "Notifications"
                        },
                        new
                        {
                            Id = 15,
                            Code = 16,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8393),
                            IsDeleted = false,
                            Name = "Client Messages"
                        },
                        new
                        {
                            Id = 16,
                            Code = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8409),
                            IsDeleted = false,
                            Name = "Roles"
                        },
                        new
                        {
                            Id = 17,
                            Code = 17,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8410),
                            IsDeleted = false,
                            Name = "AppModules"
                        },
                        new
                        {
                            Id = 18,
                            Code = 18,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8411),
                            IsDeleted = false,
                            Name = "Role Permission",
                            ParentId = 17
                        },
                        new
                        {
                            Id = 19,
                            Code = 19,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8412),
                            IsDeleted = false,
                            Name = "Resource Booking Permission"
                        },
                        new
                        {
                            Id = 20,
                            Code = 20,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(8413),
                            IsDeleted = false,
                            Name = "Resource Booking"
                        });
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authorization.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Add")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Delete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("Edit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ModuleCode")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("View")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("RoleId", "ModuleCode")
                        .IsUnique()
                        .HasFilter("[UserId] IS NULL");

                    b.HasIndex("RoleId", "ModuleCode", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1887),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 8,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 2,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1889),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 2,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 3,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1891),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 15,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 4,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1892),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 3,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 5,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1894),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 10,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 6,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1895),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 9,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 7,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1897),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 1,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 8,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1898),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 17,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 9,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1900),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 18,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 10,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1901),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 16,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 11,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1903),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 11,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 12,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1904),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 7,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 13,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1905),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 13,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 14,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1906),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 12,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 15,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1908),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 4,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 16,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1909),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 14,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 17,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1910),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 5,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 18,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1911),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 6,
                            RoleId = 1,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 19,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1912),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 3,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 20,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1914),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 4,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 21,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1915),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 15,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 22,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1917),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 7,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 23,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1918),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 5,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 24,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1920),
                            Delete = false,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 12,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 25,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1921),
                            Delete = false,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 1,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 26,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1923),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 16,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 27,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1924),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 6,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 28,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1926),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 14,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 29,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1928),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 11,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 30,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1929),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 13,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 31,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1930),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 8,
                            RoleId = 2,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 32,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1946),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 10,
                            RoleId = 2,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 42,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1947),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 19,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 43,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1949),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 20,
                            RoleId = 2,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 33,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1951),
                            Delete = false,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 7,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 34,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1952),
                            Delete = false,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 1,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 35,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1953),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 6,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 36,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1955),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 5,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 37,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1956),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 3,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 38,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1957),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 11,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 39,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1958),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 4,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 40,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1960),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 15,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        },
                        new
                        {
                            Id = 41,
                            Add = false,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1961),
                            Delete = false,
                            Edit = false,
                            IsDeleted = false,
                            ModuleCode = 8,
                            RoleId = 3,
                            Scope = 1,
                            View = true
                        },
                        new
                        {
                            Id = 44,
                            Add = true,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1962),
                            Delete = true,
                            Edit = true,
                            IsDeleted = false,
                            ModuleCode = 20,
                            RoleId = 3,
                            Scope = 0,
                            View = true
                        });
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Booking.CompanyResourceBookingPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("CompanyId", "ResourceTypeId", "EmployeeType")
                        .IsUnique();

                    b.ToTable("CompanyResourceBookingPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanBook = true,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(9035),
                            EmployeeType = "MANAGER",
                            IsDeleted = false,
                            ResourceTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            CanBook = true,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 654, DateTimeKind.Utc).AddTicks(9036),
                            EmployeeType = "TEAM_LEAD",
                            IsDeleted = false,
                            ResourceTypeId = 2
                        });
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Booking.ResourceBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCheckedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("QRCodeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("QrExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("QRCodeValue")
                        .IsUnique();

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("ResourceId", "StartTime", "EndTime");

                    b.ToTable("resourceBookings");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.ClientMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClientMessages");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.CompanyFloor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FloorId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("FloorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Scale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("FloorId");

                    b.HasIndex("CompanyId", "IsActive");

                    b.ToTable("CompanyFloors", (string)null);
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultFloorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("QRCodeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCodeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Rotation")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("CompanyId", "FloorId");

                    b.HasIndex("CompanyId", "ResourceTypeId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DefaultHeight")
                        .HasColumnType("int");

                    b.Property<int>("DefaultWidth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1683),
                            DefaultHeight = 60,
                            DefaultWidth = 60,
                            Icon = "desk.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Desk"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(1686),
                            DefaultHeight = 120,
                            DefaultWidth = 120,
                            Icon = "meetingroom.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "MeetingRoom"
                        });
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Feedbacks.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Finance.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("ReceiptId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.SubscriptionModels.CompanySubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmoutToBePaid")
                        .HasColumnType("float");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DesksLimit")
                        .HasColumnType("int");

                    b.Property<int>("EmployeesLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorsLimit")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MeetingRoomsLimit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.ToTable("CompanySubscription", (string)null);
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.SubscriptionModels.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDesks")
                        .HasColumnType("int");

                    b.Property<int>("MaxEmployees")
                        .HasColumnType("int");

                    b.Property<int>("MaxFloors")
                        .HasColumnType("int");

                    b.Property<int>("MaxMeetingRooms")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<double>("PriceMonthly")
                        .HasColumnType("float");

                    b.Property<double>("PriceYearly")
                        .HasColumnType("float");

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.SubscriptionModels.SubscriptionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountPaid")
                        .HasColumnType("float");

                    b.Property<int>("ChangeReason")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanySubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.SubscriptionModels.SubscriptionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(3485),
                            IsDeleted = false,
                            TypeName = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(3487),
                            IsDeleted = false,
                            TypeName = "Upgrade"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 19, 6, 8, 55, 655, DateTimeKind.Utc).AddTicks(3488),
                            IsDeleted = false,
                            TypeName = "Renewal"
                        });
                });

            modelBuilder.Entity("Billing", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ResourceFlow.Domain.Entities.Authentication.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourceFlow.Domain.Entities.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authentication.User", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ResourceFlow.Domain.Entities.Authentication.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authorization.AppModule", b =>
                {
                    b.HasOne("ResourceFlow.Domain.Entities.Authorization.AppModule", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authorization.RolePermission", b =>
                {
                    b.HasOne("ResourceFlow.Domain.Entities.Authentication.Roles", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourceFlow.Domain.Entities.Authentication.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Booking.CompanyResourceBookingPermission", b =>
                {
                    b.HasOne("ResourceFlow.Domain.Entities.CompanyModels.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Booking.ResourceBooking", b =>
                {
                    b.HasOne("CompanyDetails", "CompanyDetails")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourceFlow.Domain.Entities.CompanyModels.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourceFlow.Domain.Entities.CompanyModels.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyDetails");

                    b.Navigation("Resource");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.CompanyFloor", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithMany("CompanyFloors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.Employees", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourceFlow.Domain.Entities.Authentication.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("ResourceFlow.Domain.Entities.CompanyModels.Employees", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.Resource", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithMany("Resources")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourceFlow.Domain.Entities.CompanyModels.CompanyFloor", "Floor")
                        .WithMany("Resources")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourceFlow.Domain.Entities.CompanyModels.ResourceType", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Floor");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Feedbacks.Feedback", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Finance.Payment", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.SubscriptionModels.CompanySubscription", b =>
                {
                    b.HasOne("CompanyDetails", "Company")
                        .WithOne("CompanySubscription")
                        .HasForeignKey("ResourceFlow.Domain.Entities.SubscriptionModels.CompanySubscription", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResourceFlow.Domain.Entities.SubscriptionModels.Subscription", "Subscription")
                        .WithMany("CompanySubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.SubscriptionModels.Subscription", b =>
                {
                    b.HasOne("ResourceFlow.Domain.Entities.SubscriptionModels.SubscriptionType", "Type")
                        .WithMany("Types")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CompanyDetails", b =>
                {
                    b.Navigation("CompanyFloors");

                    b.Navigation("CompanySubscription")
                        .IsRequired();

                    b.Navigation("Employees");

                    b.Navigation("Resources");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authentication.Roles", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authentication.User", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.Authorization.AppModule", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.CompanyFloor", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.CompanyModels.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.SubscriptionModels.Subscription", b =>
                {
                    b.Navigation("CompanySubscriptions");
                });

            modelBuilder.Entity("ResourceFlow.Domain.Entities.SubscriptionModels.SubscriptionType", b =>
                {
                    b.Navigation("Types");
                });
#pragma warning restore 612, 618
        }
    }
}
